export const color = {
  amber: 'amber',
  blue: 'blue',
  bluegray: 'bluegray',
  coolgray: 'coolgray',
  cyan: 'cyan',
  emerald: 'emerald',
  fuchsia: 'fuchsia',
  gray: 'gray',
  green: 'green',
  indigo: 'indigo',
  lightblue: 'lightblue',
  lime: 'lime',
  orange: 'orange',
  pink: 'pink',
  purple: 'purple',
  red: 'red',
  rose: 'rose',
  teal: 'teal',
  truegray: 'truegray',
  violet: 'violet',
  warmgray: 'warmgray',
  yellow: 'yellow',
};

export type TColor = keyof typeof color;
