export const color = {
  amber: 'amber',
  blue: 'blue',
  cyan: 'cyan',
  emerald: 'emerald',
  fuchsia: 'fuchsia',
  gray: 'gray',
  green: 'green',
  indigo: 'indigo',
  lime: 'lime',
  neutral: 'neutral',
  orange: 'orange',
  pink: 'pink',
  purple: 'purple',
  red: 'red',
  rose: 'rose',
  sky: 'sky',
  slate: 'slate',
  stone: 'stone',
  teal: 'teal',
  violet: 'violet',
  yellow: 'yellow',
  zinc: 'zinc',
};

export type TColor = keyof typeof color;
